server:
  port:
    8090
  servlet:
    context-path: 
              /metrica
logging:
  level:
    org:
      hibernate:
        SQL:
          debug
    root:
      INFO
  file:
    saying-local.log
        
spring:
  datasource:
    url: 
      jdbc:mysql://localhost/db_sayings?useSSL=false
    username:
      tasksuser
    password:
      taskspassword
    driver-class-name:
      com.mysql.jdbc.Driver
  jpa:
    database-platform: 
      org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto:
      create-drop      

metrica:
  data:
    # Possible Values: dataBase | inMemory
    service:
        dataBase
       

      
      
   
  
    
